### ISSUE TITLE
any information?

### ISSUE THREAD

**Issue by langongjin** [shinjoe/Central-Pattern-Generator#1]
hi, 
I am running this CPG project. Do you have any information for me?

**Comment by shinjoe** [comment]
Hey @langongjin, this repo is no longer maintained. That being said, is there anything in particular you need help with? Are you trying to compile the project?

**Comment by langongjin** [comment]
hi, @shinjoe yes, I try to compile the project with CMAKE (I use Clion EDA on MacOS). Do you have some ideas for me to run this project? Although I read some paper about CPG, but it is better if you have some document for me.
Thanks a lot!

**Comment by shinjoe** [comment]
Sure. Are you familiar with the command line? Assuming you have `g++` or `clang`, this invocation should work, as I tested it today:

`g++ -std=c++11 main.cpp GeneticAlgo.cpp Chromosome.cpp CentralPatternGenerator.cpp Neuron.cpp RungeKutta.cpp`

Afterwards, you can run the program with `./a.out`.

Let me know if that works for you.

**Comment by langongjin** [comment]
hi, it works on my computer with the CMAKE project. Do you have more information about how CPG work in the code and what is the relations between CPG and GA? I think I have some experience about GA and know a little about CPG in general. But you know, it not easy to understand the code from other bodies without any information. Thanks a lot!

**Comment by shinjoe** [comment]
Good to hear that it compiles. As for further context, I recommend reading [this](http://www.ai-junkie.com/ga/intro/gat1.html).
